Query multiple tables
developerwaleed/Vet-Clinic-DB pull request #3
Opened 2022-08-10 18:05 UTC by developerwaleed

# Vet clinic database: query multiple tables
### ScreenShots `schema.sql`:
![image](https://user-images.githubusercontent.com/61401375/183984344-6f970f31-ef03-4de4-bc6a-946199db8da6.png)
![image](https://user-images.githubusercontent.com/61401375/183984355-d99e0e08-30af-4e5c-aec6-f0ad78e09317.png)
![image](https://user-images.githubusercontent.com/61401375/183984366-cf1df6d4-9a9a-49f0-955f-edd8ea58ffcc.png)
![image](https://user-images.githubusercontent.com/61401375/183984373-36276686-2713-4c80-9dc1-e7f7fd4cdba1.png)
![image](https://user-images.githubusercontent.com/61401375/183984386-0fc577c2-da37-4111-9c99-a1efc3636baf.png)
![image](https://user-images.githubusercontent.com/61401375/183984451-d6536951-5cbe-4752-8ac3-7694631b23d4.png)
### ScreenShots `data.sql`:
![image](https://user-images.githubusercontent.com/61401375/183984681-2632693f-e1a8-47b4-b66b-f406118a47fb.png)
![image](https://user-images.githubusercontent.com/61401375/183984695-e7b8daa8-af79-4ff7-aa6b-116786010f1e.png)
![image](https://user-images.githubusercontent.com/61401375/183984704-2a0e09d3-492e-4d1b-8a6e-e1c1c626d589.png)
![image](https://user-images.githubusercontent.com/61401375/183984731-cf991cf2-14a2-4847-b1ae-7d9e4ddb3b90.png)
### ScreenShots `queries.sql`:
![image](https://user-images.githubusercontent.com/61401375/183984792-7102794b-274b-4546-8f00-f57404dd748b.png)
![image](https://user-images.githubusercontent.com/61401375/183984807-88e00a24-ec91-4f99-855c-7112e561afdb.png)
![image](https://user-images.githubusercontent.com/61401375/183984817-473c6e7e-0b87-453a-a998-dc762b6b1eec.png)
![image](https://user-images.githubusercontent.com/61401375/183984831-bdd13c16-720b-41f7-a5c2-0b4dda169bba.png)
![image](https://user-images.githubusercontent.com/61401375/183984850-b39e94c0-0fa2-4ff4-b293-fa895dc566d9.png)
![image](https://user-images.githubusercontent.com/61401375/183984860-b13d978f-ee74-4e78-87de-e4af87675ce1.png)
![image](https://user-images.githubusercontent.com/61401375/183984872-527cc747-de4f-47c7-ba6b-d0620b76f6bb.png)

2022-08-10 18:23 UTC, Ismailco requested changes
### Hi @developerwaleed, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-10 18:23 UTC, Ismailco commented on data.sql
> +WHERE name LIKE '%mon';
- [ ] You have duplicate queries here, kindly fix this. I think you want to target `Pokemon` here not `Digimon` and also pay attention to the `species_id` if that's your intention it should be where is null not like '%mon'

2022-08-10 18:23 UTC, Ismailco commented on queries.sql
> +RIGHT JOIN species
- [ ] you should use LEFT Join here, kindly fix this

2022-08-11 06:54 UTC, developerwaleed commented on data.sql
> +WHERE name LIKE '%mon';
Thankyou 😊

2022-08-11 06:54 UTC, developerwaleed commented on queries.sql
> +RIGHT JOIN species
👍

2022-08-11 07:20 UTC, Deepakdanger approved these changes
Hi @developerwaleed, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-11 09:41 UTC, merged